# Generated by Django 4.2.27 on 2026-01-17 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('FRIEND', 'Friend'), ('CAREGIVER', 'Caregiver'), ('DOCTOR', 'Doctor'), ('OTHER', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=17)),
                ('alternate_phone', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary emergency contact')),
                ('priority_order', models.IntegerField(default=1, help_text='Order in which to contact (1 = first)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Additional information about this contact')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['priority_order'],
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('ENDOCRINE', 'Endocrine'), ('NEUROLOGICAL', 'Neurological'), ('MUSCULOSKELETAL', 'Musculoskeletal'), ('RENAL', 'Renal'), ('DIGESTIVE', 'Digestive'), ('MENTAL', 'Mental Health'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('common_symptoms', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam')], default='en', max_length=2)),
                ('health_conditions', models.JSONField(blank=True, default=list, help_text="List of chronic conditions: ['Diabetes', 'Hypertension', 'COPD']")),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of known allergies')),
                ('current_medications', models.JSONField(blank=True, default=list, help_text='List of current medications')),
                ('medical_notes', models.TextField(blank=True, help_text='Additional medical history or notes')),
                ('last_hospital_visit', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
