# Generated by Django 4.2.27 on 2026-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='abha_address',
            field=models.CharField(blank=True, help_text='ABHA address (e.g., patient@abdm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='abha_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='abha_number',
            field=models.CharField(blank=True, help_text='14-digit ABHA number (e.g., 12-3456-7890-1234)', max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='eka_patient_created',
            field=models.BooleanField(default=False, help_text='Whether patient exists in Eka.Care directory'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='eka_patient_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='eka_patient_id',
            field=models.CharField(blank=True, help_text='Eka.Care patient_id (also called oid)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='eka_sync_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store sync status and additional Eka.Care data'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_abha_verified',
            field=models.BooleanField(default=False),
        ),
    ]
