# Generated by Django 4.2.30 on 2026-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_abha_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='daily_calorie_target',
            field=models.IntegerField(blank=True, help_text='Target daily caloric intake in kcal. Null means no tracking.', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='nutrition_alert_threshold_percent',
            field=models.IntegerField(default=70, help_text='Alert if daily intake falls below this % of target (e.g. 70 = alert if <70% reached).'),
        ),
    ]
