# Generated by Django 4.2.7 on 2026-01-16 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_dailyhealthsummary_patient'),
        ('vitals', '0002_alter_vitalsign_patient'),
        ('patients', '0003_emergencycontact_healthcondition_patientprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_alter_alert_patient'),
        ('devices', '0003_alter_device_patient'),
        ('family', '0003_alter_familyaccess_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencycontact',
            unique_together={('patient', 'phone_number')},
        ),
    ]
