# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitals', '0001_initial'),
        ('medications', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='alerts.alerttype'),
        ),
        migrations.AddField(
            model_name='alertstatistics',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_statistics', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='alerts.alerttype'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='alertescalation',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertescalation',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alerttype'),
        ),
        migrations.AddField(
            model_name='alert',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vitals.datasource'),
        ),
        migrations.AddField(
            model_name='alert',
            name='medication_adherence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='medications.medicationadherence'),
        ),
        migrations.AddField(
            model_name='alert',
            name='parent_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_alerts', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='vital_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vitals.vitalreading'),
        ),
        migrations.AlterUniqueTogether(
            name='alertstatistics',
            unique_together={('patient', 'period_label', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['alert', 'channel'], name='alert_deliv_alert_i_8840f5_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['status', '-created_at'], name='alert_deliv_status_8d910e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['patient', 'status', '-created_at'], name='alerts_patient_6e98cf_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_severit_ae6d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-created_at'], name='alerts_alert_t_575fa8_idx'),
        ),
    ]
