# Generated by Django 4.2.7 on 2026-01-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HEART_RATE', 'Heart Rate'), ('BLOOD_PRESSURE', 'Blood Pressure'), ('OXYGEN_SATURATION', 'Oxygen Saturation'), ('TEMPERATURE', 'Temperature'), ('RESPIRATORY_RATE', 'Respiratory Rate'), ('STEPS', 'Steps'), ('SLEEP', 'Sleep')], max_length=50)),
                ('value', models.JSONField(help_text="Store value as {'systolic': 120, 'diastolic': 80} or {'value': 98}")),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='MANUAL', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
