# Generated by Django 4.2.7 on 2026-01-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_emergencycontact_healthcondition_patientprofile_and_more'),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patientprofile'),
        ),
    ]
