# Generated by Django 4.2.27 on 2026-01-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_abha_address_and_more'),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vitalreading',
            unique_together={('patient', 'vital_type', 'measured_at')},
        ),
    ]
