# Generated by Django 4.2.7 on 2026-01-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0004_delete_patient_patientprofile_user_and_more'),
        ('vitals', '0002_alter_vitalsign_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousVitalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('total_readings', models.IntegerField(default=0)),
                ('average_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'continuous_vital_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BLUETOOTH_DEVICE', 'Bluetooth Medical Device'), ('CLOUD_API', 'Cloud API (Fitbit/Apple Health)'), ('MANUAL_ENTRY', 'Manual Entry'), ('HOSPITAL_SYSTEM', 'Hospital System Integration'), ('CAREPAL_DEVICE', 'CarePAL Device')], max_length=20)),
                ('device_type', models.CharField(choices=[('BP_MONITOR', 'Blood Pressure Monitor'), ('PULSE_OXIMETER', 'Pulse Oximeter'), ('THERMOMETER', 'Thermometer'), ('GLUCOMETER', 'Glucose Meter'), ('WEIGHT_SCALE', 'Weight Scale'), ('HEART_RATE_MONITOR', 'Heart Rate Monitor'), ('SMARTWATCH', 'Smartwatch'), ('FITNESS_TRACKER', 'Fitness Tracker'), ('CLINICAL_MONITOR', 'Clinical Patient Monitor'), ('VENTILATOR', 'Ventilator'), ('MANUAL', 'Manual Entry')], max_length=30)),
                ('device_name', models.CharField(max_length=200)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('device_manufacturer', models.CharField(blank=True, max_length=100)),
                ('device_identifier', models.CharField(blank=True, help_text='MAC address, serial number, or API identifier', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency_minutes', models.IntegerField(blank=True, help_text='For cloud APIs, how often to sync', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(help_text='When the reading was actually taken')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the system received this reading')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('values', models.JSONField(blank=True, default=dict, help_text="{'systolic': 120, 'diastolic': 80} or {'value': 98.6}")),
                ('unit', models.CharField(max_length=20)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_severity', models.CharField(choices=[('NORMAL', 'Normal'), ('ELEVATED', 'Elevated'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('anomaly_reason', models.TextField(blank=True, help_text='Why this was flagged as anomaly')),
                ('data_quality', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="['fasting', 'post_meal', 'pre_medication', 'post_exercise']")),
                ('session_id', models.CharField(blank=True, help_text='Links continuous readings to a monitoring session', max_length=100)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='vitals.datasource')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_vitals', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_vitals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'vital_readings',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalReadingEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('previous_notes', models.TextField(blank=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('new_notes', models.TextField(blank=True)),
                ('edit_reason', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vital_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='vitals.vitalreading')),
            ],
            options={
                'db_table': 'vital_reading_edits',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalTrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_label', models.CharField(help_text="'last_24h', 'last_7days', 'last_30days'", max_length=50)),
                ('reading_count', models.IntegerField(default=0)),
                ('average_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trend_direction', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining'), ('FLUCTUATING', 'Fluctuating')], max_length=20)),
                ('trend_percentage', models.DecimalField(decimal_places=2, help_text='Percentage change compared to previous period', max_digits=5)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('critical_anomaly_count', models.IntegerField(default=0)),
                ('insights', models.JSONField(default=list, help_text='AI-generated insights about the trend')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_trends', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'vital_trend_analysis',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='VitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code like BP, HR, SPO2', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('METABOLIC', 'Metabolic'), ('PHYSICAL', 'Physical Activity'), ('BODY', 'Body Measurements')], max_length=20)),
                ('unit', models.CharField(choices=[('mmHg', 'Millimeters of Mercury'), ('bpm', 'Beats per Minute'), ('percent', 'Percentage'), ('celsius', 'Degrees Celsius'), ('fahrenheit', 'Degrees Fahrenheit'), ('mg_dl', 'Milligrams per Deciliter'), ('mmol_l', 'Millimoles per Liter'), ('breaths_min', 'Breaths per Minute'), ('kg', 'Kilograms'), ('lbs', 'Pounds'), ('steps', 'Steps'), ('hours', 'Hours')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('normal_range', models.JSONField(default=dict, help_text="Normal ranges: {'min': 60, 'max': 100, 'critical_low': 50, 'critical_high': 120}")),
                ('is_continuous', models.BooleanField(default=False, help_text='True for continuous monitoring (heart rate from watch), False for discrete (BP reading)')),
                ('requires_multiple_values', models.BooleanField(default=False, help_text='True for BP (systolic/diastolic), False for single value vitals')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vital_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='VitalSign',
        ),
        migrations.AddField(
            model_name='vitaltrendanalysis',
            name='vital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitals.vitaltype'),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='vital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='vitals.vitaltype'),
        ),
        migrations.AddField(
            model_name='continuousvitalsession',
            name='data_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitals.datasource'),
        ),
        migrations.AddField(
            model_name='continuousvitalsession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_sessions', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='continuousvitalsession',
            name='vital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitals.vitaltype'),
        ),
        migrations.AlterUniqueTogether(
            name='vitaltrendanalysis',
            unique_together={('patient', 'vital_type', 'period_label', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['patient', 'vital_type', '-measured_at'], name='vital_readi_patient_b9776b_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['patient', '-measured_at'], name='vital_readi_patient_e448fd_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['is_anomaly', 'anomaly_severity'], name='vital_readi_is_anom_aa3c31_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['session_id'], name='vital_readi_session_4a829a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('patient', 'device_identifier')},
        ),
    ]
