# Generated by Django 4.2.27 on 2026-01-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patientprofile_abha_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eka_appointment_id', models.CharField(help_text='Eka.Care appointment ID', max_length=100, unique=True)),
                ('eka_doctor_id', models.CharField(max_length=100)),
                ('eka_clinic_id', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('appointment_date', models.DateTimeField()),
                ('mode', models.CharField(choices=[('INCLINIC', 'In-Clinic Visit'), ('ONLINE', 'Online Consultation')], default='INCLINIC', max_length=20)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('booking_metadata', models.JSONField(blank=True, default=dict, help_text='Store full Eka.Care response and additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_8037cd_idx'), models.Index(fields=['status', 'appointment_date'], name='appointment_status_7c15d1_idx')],
            },
        ),
    ]
