# Generated by Django 4.2.27 on 2026-01-17 06:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(help_text="e.g., '500mg', '10ml', '2 puffs'", max_length=100)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('LIQUID', 'Liquid/Syrup'), ('INJECTION', 'Injection'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SPRAY', 'Spray'), ('PATCH', 'Patch'), ('CREAM', 'Cream/Ointment'), ('POWDER', 'Powder'), ('OTHER', 'Other')], max_length=20)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('INJECTION_IV', 'Intravenous'), ('INJECTION_IM', 'Intramuscular'), ('INJECTION_SC', 'Subcutaneous'), ('RECTAL', 'Rectal'), ('OPHTHALMIC', 'Eye'), ('OTIC', 'Ear'), ('NASAL', 'Nasal')], max_length=20)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once Daily'), ('TWICE_DAILY', 'Twice Daily (BID)'), ('THREE_TIMES_DAILY', 'Three Times Daily (TID)'), ('FOUR_TIMES_DAILY', 'Four Times Daily (QID)'), ('EVERY_4_HOURS', 'Every 4 Hours'), ('EVERY_6_HOURS', 'Every 6 Hours'), ('EVERY_8_HOURS', 'Every 8 Hours'), ('EVERY_12_HOURS', 'Every 12 Hours'), ('WEEKLY', 'Weekly'), ('TWICE_WEEKLY', 'Twice Weekly'), ('MONTHLY', 'Monthly'), ('AS_NEEDED', 'As Needed (PRN)'), ('CUSTOM', 'Custom Schedule')], max_length=20)),
                ('times_per_day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='Total duration in days', null=True)),
                ('instructions', models.TextField(help_text="Special instructions: 'Take with food', 'Take on empty stomach', etc.")),
                ('special_instructions', models.TextField(blank=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=200)),
                ('prescription_number', models.CharField(blank=True, max_length=100)),
                ('prescribed_date', models.DateField(blank=True, null=True)),
                ('quantity_prescribed', models.IntegerField(blank=True, help_text='Total quantity prescribed', null=True)),
                ('quantity_remaining', models.IntegerField(blank=True, help_text='Remaining quantity', null=True)),
                ('refills_allowed', models.IntegerField(default=0)),
                ('refills_remaining', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('discontinuation_reason', models.TextField(blank=True)),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('side_effects', models.JSONField(blank=True, default=list, help_text='List of known side effects')),
                ('interactions', models.JSONField(blank=True, default=list, help_text='List of drug interactions')),
                ('purpose', models.TextField(blank=True, help_text='What condition is this medication treating')),
                ('is_critical', models.BooleanField(default=False, help_text='Critical medication - missing doses require immediate alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('scheduled_datetime', models.DateTimeField()),
                ('actual_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('DELAYED', 'Delayed')], default='SCHEDULED', max_length=20)),
                ('confirmed_by_patient', models.BooleanField(default=False)),
                ('confirmation_method', models.CharField(blank=True, help_text="'voice', 'app', 'manual_entry', 'auto_detected'", max_length=50)),
                ('skip_reason', models.TextField(blank=True)),
                ('miss_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('side_effects_reported', models.JSONField(blank=True, default=list)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication_adherence',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdherencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(max_length=50)),
                ('total_scheduled', models.IntegerField(default=0)),
                ('total_taken', models.IntegerField(default=0)),
                ('total_missed', models.IntegerField(default=0)),
                ('total_skipped', models.IntegerField(default=0)),
                ('adherence_rate', models.DecimalField(decimal_places=2, help_text='Percentage of doses taken on time', max_digits=5)),
                ('most_missed_time', models.TimeField(blank=True, null=True)),
                ('most_missed_day', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('consecutive_misses_max', models.IntegerField(default=0)),
                ('average_delay_minutes', models.IntegerField(blank=True, help_text='Average delay when taken late', null=True)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication_adherence_patterns',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='MedicationEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('REMINDER_SENT', 'Reminder Sent'), ('FAMILY_NOTIFIED', 'Family Notified'), ('DOCTOR_NOTIFIED', 'Doctor Notified'), ('ALERT_CREATED', 'Alert Created'), ('CALL_INITIATED', 'Call Initiated')], max_length=30)),
                ('action_details', models.JSONField(default=dict, help_text='Details about the action: who was notified, call status, etc.')),
                ('escalation_reason', models.TextField()),
                ('consecutive_misses', models.IntegerField(default=1)),
                ('successful', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('response_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CONTRAINDICATED', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('clinical_effects', models.TextField(blank=True)),
                ('management', models.TextField(blank=True, help_text='How to manage this interaction')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_interactions',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('pharmacy_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('FILLED', 'Filled'), ('READY', 'Ready for Pickup'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication_refills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField()),
                ('time_label', models.CharField(blank=True, help_text="'Morning', 'Afternoon', 'Evening', 'Bedtime', etc.", max_length=50)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='[0-6] where 0=Monday, 6=Sunday. Empty list = all days')),
                ('with_food', models.BooleanField(default=False)),
                ('on_empty_stomach', models.BooleanField(default=False)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_advance_minutes', models.IntegerField(default=0, help_text='Remind X minutes before scheduled time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication')),
            ],
            options={
                'db_table': 'medication_schedules',
                'ordering': ['time_of_day'],
            },
        ),
    ]
