# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrefill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_refills_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_refills_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationinteraction',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationinteraction',
            name='medication_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_med1', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationinteraction',
            name='medication_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_med2', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationescalation',
            name='adherence_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='medications.medicationadherence'),
        ),
        migrations.AddField(
            model_name='medicationescalation',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationadherencepattern',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adherence_patterns', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationadherencepattern',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_patterns', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='medicationadherence',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationadherence',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to='medications.medicationschedule'),
        ),
        migrations.AddField(
            model_name='medication',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='discontinued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discontinued_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationinteraction',
            unique_together={('medication_1', 'medication_2')},
        ),
        migrations.AlterUniqueTogether(
            name='medicationadherencepattern',
            unique_together={('patient', 'medication', 'period_label', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='medicationadherence',
            index=models.Index(fields=['medication', 'scheduled_date'], name='medication__medicat_bde8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadherence',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='medication__status_eca140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationadherence',
            unique_together={('medication', 'scheduled_datetime')},
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'status'], name='medications_patient_9bf09f_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['status', 'start_date'], name='medications_status_b35cdb_idx'),
        ),
    ]
