# Generated by Django 4.2.27 on 2026-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='eka_drug_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='eka_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='eka_prescription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medication',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('EKA_CARE', 'Imported from Eka.Care'), ('HOSPITAL', 'Hospital System')], default='MANUAL', max_length=20),
        ),
    ]
