# Generated by Django 4.2.30 on 2026-06-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_add_confirmation_method_source_log'),
        ('medications', '0003_medication_eka_drug_id_medication_eka_imported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadherence',
            name='source_activity_log',
            field=models.ForeignKey(blank=True, help_text='The activity log entry that caused this adherence record to be written.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adherence_updates', to='agent.patientactivitylog'),
        ),
        migrations.AlterField(
            model_name='medicationadherence',
            name='confirmation_method',
            field=models.CharField(blank=True, choices=[('DEVICE', 'Smart Device'), ('MANUAL', 'Manual Entry'), ('AI_VERBAL', 'AI Verbal Confirmation'), ('MONITOR_AGENT', 'Medication Monitor Agent'), ('FAMILY', 'Family Reported')], default='MANUAL', max_length=20),
        ),
    ]
