# Generated by Django 4.2.30 on 2026-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_add_confirmation_method_source_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dose_times',
            field=models.JSONField(blank=True, default=list, help_text='[{"time":"08:00","label":"Morning"}, ...] Auto-set from frequency. Editable per patient preference.'),
        ),
    ]
