# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_steps', models.IntegerField(default=0)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('avg_blood_pressure', models.JSONField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(default=0.0)),
                ('calories_burned', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
