# Generated by Django 4.2.7 on 2026-01-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyhealthsummary',
            unique_together={('patient', 'date')},
        ),
    ]
