# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('VISIT', 'In-Person Visit'), ('CALL', 'Phone Call Check-in'), ('MEDICATION_HELP', 'Medication Assistance'), ('APPOINTMENT', 'Medical Appointment'), ('ACTIVITY', 'Activity/Exercise'), ('MEAL', 'Meal Preparation'), ('OTHER', 'Other Care Task')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(blank=True, default=dict, help_text="{'frequency': 'daily/weekly/monthly', 'interval': 1, 'end_date': 'YYYY-MM-DD'}")),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=60)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'care_schedules',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='FamilyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEWED_DASHBOARD', 'Viewed Dashboard'), ('VIEWED_VITALS', 'Viewed Vitals'), ('VIEWED_MEDICATIONS', 'Viewed Medications'), ('VIEWED_ALERTS', 'Viewed Alerts'), ('ACKNOWLEDGED_ALERT', 'Acknowledged Alert'), ('ADDED_NOTE', 'Added Note'), ('UPDATED_MEDICATION', 'Updated Medication'), ('INVITED_MEMBER', 'Invited Family Member'), ('UPDATED_PERMISSIONS', 'Updated Permissions'), ('DOWNLOADED_REPORT', 'Downloaded Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'family_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('GENERAL', 'General Message'), ('ALERT_DISCUSSION', 'Alert Discussion'), ('CARE_COORDINATION', 'Care Coordination'), ('QUESTION', 'Question'), ('UPDATE', 'Status Update')], default='GENERAL', max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read_by', models.JSONField(blank=True, default=list, help_text='List of family member IDs who read this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'family_communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_widgets', models.JSONField(default=list, help_text="List of widget IDs to show: ['vitals_chart', 'medication_schedule', 'alerts', 'notes']")),
                ('widget_order', models.JSONField(default=list, help_text='Order of widgets on dashboard')),
                ('default_time_range', models.CharField(default='7days', help_text="Default time range for charts: '24hours', '7days', '30days', '90days'", max_length=20)),
                ('show_vital_trends', models.BooleanField(default=True)),
                ('show_medication_adherence', models.BooleanField(default=True)),
                ('show_alert_history', models.BooleanField(default=True)),
                ('notify_on_critical_alerts', models.BooleanField(default=True)),
                ('notify_on_missed_medications', models.BooleanField(default=True)),
                ('notify_on_schedule_reminders', models.BooleanField(default=True)),
                ('daily_summary_enabled', models.BooleanField(default=False)),
                ('daily_summary_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'family_dashboard_settings',
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invitee_phone', models.CharField(blank=True, max_length=20)),
                ('invitee_name', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('GRANDCHILD', 'Grandchild'), ('GRANDPARENT', 'Grandparent'), ('OTHER_RELATIVE', 'Other Relative'), ('FRIEND', 'Friend'), ('CAREGIVER', 'Professional Caregiver'), ('GUARDIAN', 'Legal Guardian')], max_length=30)),
                ('access_level', models.CharField(choices=[('VIEW_ONLY', 'View Only'), ('BASIC', 'Basic Access'), ('FULL', 'Full Access'), ('ADMIN', 'Admin Access')], default='BASIC', max_length=20)),
                ('personal_message', models.TextField(blank=True)),
                ('invitation_token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'family_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('GRANDCHILD', 'Grandchild'), ('GRANDPARENT', 'Grandparent'), ('OTHER_RELATIVE', 'Other Relative'), ('FRIEND', 'Friend'), ('CAREGIVER', 'Professional Caregiver'), ('GUARDIAN', 'Legal Guardian')], max_length=30)),
                ('relationship_details', models.TextField(blank=True, help_text='Additional details about the relationship')),
                ('access_level', models.CharField(choices=[('VIEW_ONLY', 'View Only'), ('BASIC', 'Basic Access'), ('FULL', 'Full Access'), ('ADMIN', 'Admin Access')], default='BASIC', max_length=20)),
                ('can_view_vitals', models.BooleanField(default=True)),
                ('can_view_medications', models.BooleanField(default=True)),
                ('can_view_alerts', models.BooleanField(default=True)),
                ('can_view_medical_history', models.BooleanField(default=False)),
                ('can_acknowledge_alerts', models.BooleanField(default=True)),
                ('can_add_notes', models.BooleanField(default=True)),
                ('can_manage_medications', models.BooleanField(default=False)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('is_primary_caregiver', models.BooleanField(default=False, help_text='Primary point of contact for this patient')),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'family_members',
                'ordering': ['-is_primary_caregiver', 'relationship'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('OBSERVATION', 'General Observation'), ('CONCERN', 'Concern'), ('MEDICATION', 'Medication Related'), ('APPOINTMENT', 'Appointment Related'), ('SYMPTOM', 'Symptom Report'), ('BEHAVIOR', 'Behavior Change'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Visible only to creator and primary caregiver')),
                ('is_important', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs/IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='family.familymember')),
            ],
            options={
                'db_table': 'family_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
