# Generated by Django 4.2.7 on 2026-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('CHILD', 'Child'), ('SPOUSE', 'Spouse'), ('OTHER', 'Other')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
