# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('patients', '0001_initial'),
        ('family', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familynote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_notes', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='familynote',
            name='related_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_notes', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='familynote',
            name='related_medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_notes', to='medications.medication'),
        ),
    ]
