# Generated by Django 4.2.7 on 2026-01-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyaccess',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_access', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='familyaccess',
            unique_together={('patient', 'family_member')},
        ),
    ]
