# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitals', '0001_initial'),
        ('patients', '0001_initial'),
        ('family', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familynote',
            name='related_vital_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_notes', to='vitals.vitalreading'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_family_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_invitations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_invitations', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='familydashboardsettings',
            name='family_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to='family.familymember'),
        ),
        migrations.AddField(
            model_name='familycommunication',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='family.familycommunication'),
        ),
        migrations.AddField(
            model_name='familycommunication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_communications', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='familycommunication',
            name='related_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_communications', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='familycommunication',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='family.familynote'),
        ),
        migrations.AddField(
            model_name='familycommunication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='family.familymember'),
        ),
        migrations.AddField(
            model_name='familyactivitylog',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='family.familymember'),
        ),
        migrations.AddField(
            model_name='familyactivitylog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_activity_logs', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='careschedule',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_care_tasks', to='family.familymember'),
        ),
        migrations.AddField(
            model_name='careschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_care_tasks', to='family.familymember'),
        ),
        migrations.AddField(
            model_name='careschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_schedules', to='patients.patientprofile'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['patient', 'is_active'], name='family_memb_patient_f0d65e_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'is_active'], name='family_memb_user_id_66e60f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('user', 'patient')},
        ),
        migrations.AddIndex(
            model_name='familyactivitylog',
            index=models.Index(fields=['family_member', '-created_at'], name='family_acti_family__c47c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='familyactivitylog',
            index=models.Index(fields=['patient', '-created_at'], name='family_acti_patient_0ee8ab_idx'),
        ),
    ]
