# Generated by Django 4.2.30 on 2026-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='can_view_activity_log',
            field=models.BooleanField(default=True),
        ),
    ]
