# Generated by Django 4.2.27 on 2026-01-17 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_ALERT', 'Create Alert'), ('UPDATE_MEDICATION', 'Update Medication'), ('RECORD_VITAL', 'Record Vital Sign'), ('CALL_EMERGENCY', 'Call Emergency Contact'), ('CALL_FAMILY', 'Call Family Member'), ('SEND_SMS', 'Send SMS'), ('SCHEDULE_TASK', 'Schedule Task'), ('LOG_ACTIVITY', 'Log Activity'), ('UPDATE_PATIENT', 'Update Patient Info'), ('QUERY_DATA', 'Query Patient Data'), ('GENERATE_REPORT', 'Generate Report'), ('MEDICATION_REMINDER', 'Send Medication Reminder'), ('ESCALATE_ALERT', 'Escalate Alert')], max_length=30)),
                ('function_called', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters passed to the function')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked by Permission')], default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Result returned from the function')),
                ('error_message', models.TextField(blank=True)),
                ('requires_permission', models.BooleanField(default=True)),
                ('permission_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_agent_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Hash of the query/context', max_length=200)),
                ('query', models.TextField(help_text='Original query')),
                ('response', models.TextField(help_text='Cached response')),
                ('context_hash', models.CharField(help_text='Hash of context used', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('tokens_saved', models.IntegerField(default=0)),
                ('cost_saved_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('patient', models.ForeignKey(blank=True, help_text='Patient-specific cache, null for global cache', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_cache', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'agent_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SESSION_STARTED', 'Session Started'), ('SESSION_ENDED', 'Session Ended'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_RECEIVED', 'Message Received'), ('FUNCTION_CALLED', 'Function Called'), ('ACTION_EXECUTED', 'Action Executed'), ('ERROR_OCCURRED', 'Error Occurred'), ('ESCALATION_TRIGGERED', 'Escalation Triggered'), ('MEMORY_CREATED', 'Memory Created'), ('MEMORY_ACCESSED', 'Memory Accessed')], max_length=30)),
                ('event_data', models.JSONField(default=dict, help_text='Detailed event information')),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_event_logs', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'agent_event_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('PREFERENCE', 'User Preference'), ('CONCERN', 'Health Concern'), ('INSTRUCTION', 'Special Instruction'), ('CONTEXT', 'Conversation Context'), ('GOAL', 'Health Goal')], max_length=20)),
                ('key', models.CharField(help_text='Memory key/identifier', max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Memory expires after this time (null = never)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AGENT', 'AI Agent'), ('SYSTEM', 'System')], max_length=10)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('FUNCTION_CALL', 'Function Call'), ('FUNCTION_RESULT', 'Function Result'), ('SYSTEM_EVENT', 'System Event')], default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('audio_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('function_parameters', models.JSONField(blank=True, default=dict)),
                ('function_result', models.JSONField(blank=True, default=dict)),
                ('tokens', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'agent_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_type', models.CharField(choices=[('VOICE_CALL', 'Voice Call'), ('WEBSOCKET', 'WebSocket Chat'), ('SCHEDULED_CHECKIN', 'Scheduled Check-in'), ('EMERGENCY', 'Emergency Intervention'), ('FAMILY_QUERY', 'Family Member Query')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error'), ('INTERRUPTED', 'Interrupted')], default='ACTIVE', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('bn', 'Bengali')], default='en', max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('audio_input_seconds', models.IntegerField(default=0)),
                ('audio_output_seconds', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated cost based on Gemini pricing', max_digits=10)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='What patient data was sent to AI for this session')),
                ('context_size_tokens', models.IntegerField(default=0)),
                ('outcome', models.CharField(blank=True, help_text='Summary of what was accomplished', max_length=200)),
                ('actions_taken_count', models.IntegerField(default=0)),
                ('alerts_created', models.IntegerField(default=0)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_call_status', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional session metadata')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='patients.patientprofile')),
                ('user', models.ForeignKey(help_text='User who initiated (patient or family member)', on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories_created', to='agent.agentsession'),
        ),
        migrations.AddField(
            model_name='agenteventlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='agent.agentsession'),
        ),
        migrations.AddField(
            model_name='agentaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='agent.agentsession'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['patient', '-started_at'], name='agent_sessi_patient_215612_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['session_type', 'status'], name='agent_sessi_session_81e4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['session_id'], name='agent_sessi_session_43a358_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['session', 'timestamp'], name='agent_messa_session_a319ba_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['patient', 'memory_type'], name='agent_memor_patient_b4cfb4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['key'], name='agent_memor_key_099db2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentmemory',
            unique_together={('patient', 'key')},
        ),
        migrations.AddIndex(
            model_name='agenteventlog',
            index=models.Index(fields=['patient', '-timestamp'], name='agent_event_patient_1e41cd_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteventlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='agent_event_event_t_db49a5_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteventlog',
            index=models.Index(fields=['session', '-timestamp'], name='agent_event_session_c9d6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcacheentry',
            index=models.Index(fields=['cache_key', 'expires_at'], name='agent_cache_cache_k_87f821_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcacheentry',
            index=models.Index(fields=['patient', 'cache_key'], name='agent_cache_patient_3296d6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['session', '-created_at'], name='agent_actio_session_59d3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['action_type', 'status'], name='agent_actio_action__acc299_idx'),
        ),
    ]
