# Generated by Django 4.2.30 on 2026-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_patient_activity_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientactivitylog',
            new_name='patient_act_patient_b274f1_idx',
            old_name='pat_act_patient_obs_idx',
        ),
        migrations.RenameIndex(
            model_name='patientactivitylog',
            new_name='patient_act_activit_2b02ae_idx',
            old_name='pat_act_type_obs_idx',
        ),
        migrations.RenameIndex(
            model_name='patientactivitylog',
            new_name='patient_act_is_nota_96c90e_idx',
            old_name='pat_act_notable_obs_idx',
        ),
        migrations.RenameIndex(
            model_name='patientactivitylog',
            new_name='patient_act_session_711be3_idx',
            old_name='pat_act_session_idx',
        ),
        migrations.AlterField(
            model_name='patientactivitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured additional details (meal items, symptom severity, etc.)'),
        ),
    ]
