# Generated by Django 4.2.30 on 2026-06-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_abha_address_and_more'),
        ('agent', '0005_rename_pat_act_patient_obs_idx_patient_act_patient_b274f1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The exact question or prompt to inject into the Live AI session.')),
                ('context', models.TextField(blank=True, help_text='Internal context for why this question is being asked. Not shown to the patient — used to help the AI frame the question naturally.')),
                ('source', models.CharField(choices=[('MEDICATION_AGENT', 'Medication Monitor Agent'), ('SYSTEM', 'System'), ('DOCTOR', 'Doctor'), ('FAMILY', 'Family Member')], default='SYSTEM', max_length=30)),
                ('source_object_type', models.CharField(blank=True, help_text='Optional: model name of the object that triggered this question.', max_length=50)),
                ('source_object_id', models.IntegerField(blank=True, help_text='Optional: PK of the triggering object for audit trail.', null=True)),
                ('priority', models.IntegerField(default=5, help_text='1 = highest priority (ask first), 10 = lowest. Live AI asks pending questions in priority order.')),
                ('asked', models.BooleanField(default=False)),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If the question is still pending after this time, discard it.', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_questions', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'pending_questions',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
