# Generated by Django 4.2.30 on 2026-06-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientprofile_daily_calorie_target_and_more'),
        ('agent', '0006_add_confirmation_method_source_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingquestion',
            name='source',
            field=models.CharField(choices=[('MEDICATION_AGENT', 'Medication Monitor Agent'), ('NUTRITION_AGENT', 'Nutrition Monitor Agent'), ('SYSTEM', 'System'), ('DOCTOR', 'Doctor'), ('FAMILY', 'Family Member')], default='SYSTEM', max_length=30),
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.DateTimeField(help_text='When the meal was consumed (may differ from when it was logged)')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('description', models.TextField(help_text='What the patient said they ate')),
                ('estimated_kcal', models.IntegerField(blank=True, help_text='AI-estimated kilocalories for this meal', null=True)),
                ('items', models.JSONField(blank=True, default=list, help_text="Parsed food items: [{'name': 'rice', 'qty': '1 cup', 'kcal': 200}]")),
                ('appetite', models.CharField(blank=True, help_text="GOOD | POOR | NORMAL — patient's reported appetite", max_length=10)),
                ('below_threshold', models.BooleanField(default=False, help_text='True if daily total was below patient threshold when this log was saved')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to='patients.patientprofile')),
                ('source_activity_log', models.OneToOneField(blank=True, help_text='The MEAL activity log entry that triggered this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_log', to='agent.patientactivitylog')),
            ],
            options={
                'db_table': 'nutrition_logs',
                'ordering': ['-meal_time'],
                'indexes': [models.Index(fields=['patient', '-meal_time'], name='nutrition_l_patient_7c590a_idx')],
            },
        ),
    ]
