# Generated by Django 4.2.27 on 2026-01-17 06:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('connected_at', models.DateTimeField()),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='RSSI value', null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('readings_received', models.IntegerField(default=0)),
                ('bytes_transferred', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('device_firmware', models.CharField(blank=True, max_length=50)),
                ('device_hardware', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'bluetooth_device_sessions',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudAPICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('provider_user_id', models.CharField(blank=True, max_length=200)),
                ('provider_user_info', models.JSONField(blank=True, default=dict, help_text='Additional user info from provider')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consent_given_at', models.DateTimeField(auto_now_add=True)),
                ('consent_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cloud_api_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FITBIT', 'Fitbit'), ('GOOGLE_FIT', 'Google Fit'), ('APPLE_HEALTH', 'Apple Health'), ('SAMSUNG_HEALTH', 'Samsung Health'), ('WITHINGS', 'Withings'), ('GARMIN', 'Garmin Connect'), ('POLAR', 'Polar Flow')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=500)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('authorization_url', models.URLField(max_length=500)),
                ('token_url', models.URLField(max_length=500)),
                ('api_base_url', models.URLField(max_length=500)),
                ('scopes', models.JSONField(default=list, help_text='Required OAuth scopes')),
                ('supports_webhooks', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('rate_limit_per_hour', models.IntegerField(default=150)),
                ('sync_interval_minutes', models.IntegerField(default=15)),
                ('supported_vitals', models.JSONField(default=list, help_text="List of vital types this provider supports: ['heart_rate', 'steps', 'sleep']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cloud_providers',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='DataConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_time', models.DateTimeField()),
                ('time_window_minutes', models.IntegerField(default=5, help_text='Conflict if readings within this window differ significantly')),
                ('readings', models.JSONField(default=list, help_text='List of conflicting readings with source and value')),
                ('max_deviation', models.DecimalField(decimal_places=2, help_text='Maximum difference between readings', max_digits=10)),
                ('deviation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resolution_method', models.CharField(choices=[('PENDING', 'Pending Review'), ('USE_PRIMARY', 'Use Primary Device'), ('USE_AVERAGE', 'Use Average'), ('USE_LATEST', 'Use Latest'), ('MANUAL', 'Manual Selection'), ('IGNORE', 'Ignore Conflict')], default='PENDING', max_length=20)),
                ('selected_reading_id', models.IntegerField(blank=True, null=True)),
                ('resolved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_conflicts',
                'ordering': ['-conflict_time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_at', models.DateTimeField()),
                ('calibration_type', models.CharField(help_text="'baseline', 'offset_adjustment', 'reference_comparison'", max_length=50)),
                ('calibration_values', models.JSONField(default=dict, help_text='Calibration parameters and adjustments')),
                ('reference_device', models.CharField(blank=True, max_length=200)),
                ('reference_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('device_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deviation', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between device and reference', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('next_calibration_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_calibrations',
                'ordering': ['-calibrated_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.JSONField(default=list, help_text='List of data_source IDs in priority order: [3, 1, 5]')),
                ('use_average_if_close', models.BooleanField(default=False, help_text="Average values if they're within threshold")),
                ('threshold_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text="Consider values 'close' if within this percentage", max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_priorities',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=200, unique=True)),
                ('callback_url', models.URLField(max_length=500)),
                ('event_types', models.JSONField(default=list, help_text="List of event types: ['activity', 'sleep', 'body']")),
                ('verification_code', models.CharField(blank=True, max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Verification'), ('FAILED', 'Failed'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='devices.cloudapicredential')),
            ],
            options={
                'db_table': 'webhook_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('WEBHOOK', 'Webhook'), ('REAL_TIME', 'Real-time')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('sync_from_date', models.DateTimeField(blank=True, null=True)),
                ('sync_to_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional sync metadata: API calls made, rate limits, etc.')),
                ('cloud_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='devices.cloudapicredential')),
            ],
            options={
                'db_table': 'device_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
