# Generated by Django 4.2.27 on 2026-01-17 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
        ('vitals', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesynclog',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='vitals.datasource'),
        ),
        migrations.AddField(
            model_name='devicepriority',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_priorities', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='devicepriority',
            name='vital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitals.vitaltype'),
        ),
        migrations.AddField(
            model_name='devicecalibration',
            name='calibrated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicecalibration',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='vitals.datasource'),
        ),
        migrations.AddField(
            model_name='dataconflict',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_conflicts', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='dataconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataconflict',
            name='vital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitals.vitaltype'),
        ),
        migrations.AddField(
            model_name='cloudapicredential',
            name='data_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_credential', to='vitals.datasource'),
        ),
        migrations.AddField(
            model_name='cloudapicredential',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_credentials', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='cloudapicredential',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='devices.cloudprovider'),
        ),
        migrations.AddField(
            model_name='bluetoothdevicesession',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluetooth_sessions', to='vitals.datasource'),
        ),
        migrations.AddIndex(
            model_name='devicesynclog',
            index=models.Index(fields=['data_source', '-started_at'], name='device_sync_data_so_6b9ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesynclog',
            index=models.Index(fields=['status', '-started_at'], name='device_sync_status_8f9f37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicepriority',
            unique_together={('patient', 'vital_type')},
        ),
        migrations.AlterUniqueTogether(
            name='cloudapicredential',
            unique_together={('patient', 'provider')},
        ),
    ]
