name: carepal_connect
description: "CarePal Connect — Remote viewer for Doctors and Family members."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  google_fonts: ^7.0.2
  fl_chart: ^0.66.0

  # Utilities
  intl: ^0.18.1
  table_calendar: ^3.0.9
  url_launcher: ^6.3.2
  permission_handler: ^11.3.0
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
