# Generated by Django 4.2.27 on 2026-01-29 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patientprofile_abha_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABHAProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abha_address', models.CharField(db_index=True, max_length=50, unique=True)),
                ('abha_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('abdm_access_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('auto_approve_carepal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abha_profile', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'ABHA Profile',
                'verbose_name_plural': 'ABHA Profiles',
                'db_table': 'abdm_abha_profiles',
            },
        ),
        migrations.CreateModel(
            name='CareContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('vitals', 'Vital Signs Monitoring'), ('medications', 'Medication Records'), ('ai_consultations', 'AI Assistant Consultations'), ('emergency', 'Emergency Incidents'), ('lab_reports', 'Lab Reports'), ('external', 'External Provider Records')], max_length=50)),
                ('context_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_linked', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('link_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('external_hip_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_hip_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abha_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_contexts', to='abdm.abhaprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_contexts', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Care Context',
                'verbose_name_plural': 'Care Contexts',
                'db_table': 'abdm_care_contexts',
            },
        ),
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('consent_request_id', models.CharField(max_length=100, unique=True)),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_id', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abha_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='abdm.abhaprofile')),
                ('care_contexts', models.ManyToManyField(related_name='consent_requests', to='abdm.carecontext')),
            ],
            options={
                'verbose_name': 'Consent Request',
                'verbose_name_plural': 'Consent Requests',
                'db_table': 'abdm_consent_requests',
            },
        ),
        migrations.CreateModel(
            name='HealthRecordTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('push', 'Push to External HIU'), ('pull', 'Pull from External HIP')], max_length=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('data_size_bytes', models.IntegerField(default=0)),
                ('fhir_format', models.BooleanField(default=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('care_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abdm.carecontext')),
                ('consent_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='abdm.consentrequest')),
            ],
            options={
                'verbose_name': 'Health Record Transfer',
                'verbose_name_plural': 'Health Record Transfers',
                'db_table': 'abdm_health_record_transfers',
            },
        ),
        migrations.CreateModel(
            name='ABDMSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=10)),
                ('otp_hash', models.CharField(max_length=256)),
                ('session_type', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abha_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abdm.abhaprofile')),
                ('care_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abdm.carecontext')),
            ],
            options={
                'verbose_name': 'ABDM Session',
                'verbose_name_plural': 'ABDM Sessions',
                'db_table': 'abdm_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='carecontext',
            index=models.Index(fields=['patient', 'context_type'], name='abdm_care_c_patient_5f00e7_idx'),
        ),
        migrations.AddIndex(
            model_name='carecontext',
            index=models.Index(fields=['context_id'], name='abdm_care_c_context_4b15e9_idx'),
        ),
    ]
