# Generated by Django 4.2.30 on 2026-06-05 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_abha_address_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Physician'), ('SPECIALIST', 'Specialist'), ('NURSE', 'Nurse / Paramedic'), ('CONSULTANT', 'Consultant')], default='PRIMARY', max_length=20)),
                ('can_view_vitals', models.BooleanField(default=True)),
                ('can_view_activity_log', models.BooleanField(default=True)),
                ('can_view_medications', models.BooleanField(default=True)),
                ('can_edit_medications', models.BooleanField(default=True)),
                ('can_view_alerts', models.BooleanField(default=True)),
                ('can_view_appointments', models.BooleanField(default=True)),
                ('can_edit_appointments', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_relationships', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_relationships', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'clinical_relationships',
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
